version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
    - "5432:5432"

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "4747:8080"