openapi: '3.0.0'
info:
  version: '1'
  title: 'Backend'
  description: Donate gifts backend
servers:
  - url: https://ts-backend-dev-vbamtom7tq-uc.a.run.app/
    description: dev server

paths:
  /user:
    get:
      summary: Get user data of logged in user
      responses:
        '200':
          description: the logged in user or nothing if no user exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: create user with firebase data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
              required:
                - firstName
      responses:
        '200':
          description: the logged in user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: update user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '200':
          description: the logged in user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          $ref: '#/components/schemas/SpacecraftId'
        name:
          type: string
        type:
          type: string
          enum:
            - capsule
            - probe
            - satellite
            - spaceplane
            - station
        description:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    token:
      type: apiKey
      in: header
      name: authorization
      description: Firebase token in format "Bearer token"
security:
  - token: []